# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: izdeploy

before:
  hooks:
    - go mod tidy

builds:
  - id: izdeploy
    main: ./cmd/izdeploy
    binary: izdeploy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}

  - id: izdeploy-agent
    main: ./cmd/izdeploy-agent
    binary: izdeploy-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}

  - id: izdeploy-watchdog
    main: ./cmd/izdeploy-watchdog
    binary: izdeploy-watchdog
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}

archives:
  - id: izdeploy
    ids:
      - izdeploy
    name_template: "izdeploy_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

  - id: izdeploy-agent
    ids:
      - izdeploy-agent
    name_template: "izdeploy-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

  - id: izdeploy-watchdog
    ids:
      - izdeploy-watchdog
    name_template: "izdeploy-watchdog_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
